py_client: allow user-supplied requests.Session object
Parquery/swagger-to pull request #92
Opened 2020-09-09 08:32 UTC by falzm

This change introduces a new optional `session` parameter to the
`py_client.RemoteCaller` constructor, allowing users to pass a custom
python-requests `Session` object.

Fixes #90.

2020-09-09 14:34 UTC, mristin requested changes
Thanks for the code, @falzm!
(I changed the title to make it conform to the other messages in the history.)

It seems that the push/pull request checks were not run at all -- otherwise at least the tests must have failed. I updated the workflows (https://github.com/Parquery/swagger-to/pull/93). Could you please try to rebase to the latest master and see if the checks run?

Otherwise, you can run manually:
```
./precommit.py
```

If you want to automatically format the code:
```
./precommit.py --overwrite
```

2020-09-09 14:34 UTC, mristin commented on swagger_to/py_client.py
> +    def __init__(self, url_prefix: str, auth: Optional[requests.auth.AuthBase] = None, session: Optional[requests.Session] = None) -> None:
Please fix the line width.

2020-09-09 14:35 UTC, mristin commented on swagger_to/py_client.py
> +    def __init__(self, url_prefix: str, auth: Optional[requests.auth.AuthBase] = None, session: Optional[requests.Session] = None) -> None:
Please fix the line width.

```suggestion
    def __init__(
        self, 
        url_prefix: str, 
        auth: Optional[requests.auth.AuthBase] = None, 
        session: Optional[requests.Session] = None) -> None:
```

2020-09-09 15:11 UTC, falzm commented
@mristin the issue seems to be related to the fact that the code generated from now on looks different from before this change, and all the test files are now triggering an error:

```console
$ ./precommit.py
There are 1 file(s) that need to be individually checked...
One or more checks failed for tests/test_py_client.py:
Failed to pylint tests/test_py_client.py:
Output:
************* Module test_py_client
tests/test_py_client.py:17:8: C0103: Attribute name "maxDiff" doesn't conform to snake_case naming style (invalid-name)

------------------------------------------------------------------
Your code has been rated at 9.82/10 (previous run: 9.82/10, +0.00)



Error:

Running unit tests...
...........F........
======================================================================
FAIL: test_that_it_works (test_py_client.TestPyClient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marc/Desktop/swagger-to/tests/test_py_client.py", line 49, in test_that_it_works
    self.assertEqual(expected, text)
AssertionError: '#!/u[6385 chars]it__(self, url_prefix: str, auth: Optional[req[974 chars]G!\n' != '#!/u[6385 chars]it__(\n        self, \n        url_prefix: str[1187 chars]G!\n'
  #!/usr/bin/env python3
  # Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!
  """Implements the client for test."""

  # ...

  class RemoteCaller:
      """Executes the remote calls to the server."""

-     def __init__(self, url_prefix: str, auth: Optional[requests.auth.AuthBase] = None) -> None:
+     def __init__(
+         self,
+         url_prefix: str,
+         auth: Optional[requests.auth.AuthBase] = None,
+         session: Optional[requests.Session] = None) -> None:
          self.url_prefix = url_prefix
          self.auth = auth
+         self.session = session
+
+         if not self.session:
+             self.session = requests.Session()
+             self.session.auth = self.auth

      def test_me(
              self,
              test_object: Optional[TestObject] = None) -> TestObject:
          """
          Is a test endpoint.

          :param test_object:

          :return: a test object
          """
          url = self.url_prefix + '/products'

          data = None  # type: Optional[Any]
          if test_object != None:
              data = to_jsonable(
                  test_object,
                  expected=[TestObject])

-         resp = requests.request(
?                ^ ^^  -
+         resp = self.session.request(
?                ^ ^^^^   +++
              method='get',
              url=url,
              json=data,
-             auth=self.auth,
          )

          with contextlib.closing(resp):
              resp.raise_for_status()
              return from_obj(
                  obj=resp.json(),
                  expected=[TestObject])


  # Automatically generated file by swagger_to. DO NOT EDIT OR APPEND ANYTHING!


----------------------------------------------------------------------
Ran 20 tests in 0.238s

FAILED (failures=1)
One or more checks failed.
```

Shall I go ahead and update all the test files (for the python client) so they match the new output?

2020-09-09 15:39 UTC, mristin commented
@falzm please do update the generated files. 

Could you try to run a generated client against a server to see if it all works as you expected?

2020-09-10 12:20 UTC, falzm commented
@mristin tests are now passing.

Here is a real-world proof that it works when trying with the [Exoscale V2 API](https://bump.sh/doc/exoscale-api):

```console
# Exoscale API V2 OAS sample available here: https://gist.github.com/falzm/5e36c75957da916a041f46171d4319a1
$ PYTHONPATH=. python bin/swagger_to_py_client.py --swagger_path=$HOME/Desktop/snapshots.oas.yaml --outpath exo.py
Generated python client code in: exo.py

$ python
Python 3.8.3 (default, Jul 10 2020, 10:49:53)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import exo
>>> import os
>>> import requests
>>> from exoscale_auth import ExoscaleV2Auth
>>>
>>> sess = requests.Session()
>>> sess.auth = ExoscaleV2Auth(os.getenv("EXOSCALE_API_KEY"), os.getenv("EXOSCALE_API_SECRET"))
>>> rc = exo.RemoteCaller("https://api-ch-gva-2.exoscale.com/v2.alpha", session=sess)
>>> print(rc.list_snapshots())
b'{"snapshots":[{"created-at":"2020-09-10T06:25:04Z","name":"irc0_ROOT-634489_20200910042504","id":"f7c0a3d6-26ee-4b5a-82a1-13fc5f31fad0","state":"ready","instance":{"id":"e8db5c21-da06-4bb0-adb1-2f914972e158","name":"irc0","state":"running"}},{"created-at":"2020-09-09T06:25:05Z","name":"irc0_ROOT-634489_20200909042505","id":"ba134ec3-65c2-4b2e-822b-8cf1b4cee025","state":"ready","instance":{"id":"e8db5c21-da06-4bb0-adb1-2f914972e158","name":"irc0","state":"running"}},{"created-at":"2020-09-07T06:25:04Z","name":"irc0_ROOT-634489_20200907042504","id":"f71a7768-b1a2-49fe-affc-3cda0dbe382b","state":"ready","instance":{"id":"e8db5c21-da06-4bb0-adb1-2f914972e158","name":"irc0","state":"running"}},{"created-at":"2020-09-06T06:25:09Z","name":"irc0_ROOT-634489_20200906042509","id":"cdf099a7-ade4-4436-9243-4b2115f930c5","state":"ready","instance":{"id":"e8db5c21-da06-4bb0-adb1-2f914972e158","name":"irc0","state":"running"}},{"created-at":"2020-09-05T06:25:04Z","name":"irc0_ROOT-634489_20200905042504","id":"83d866ac-f25b-4e78-bea5-f0e7de6b3b2d","state":"ready","instance":{"id":"e8db5c21-da06-4bb0-adb1-2f914972e158","name":"irc0","state":"running"}},{"created-at":"2020-09-04T06:25:04Z","name":"irc0_ROOT-634489_20200904042504","id":"89f3327d-9907-4d5e-82b6-de1271e5230c","state":"ready","instance":{"id":"e8db5c21-da06-4bb0-adb1-2f914972e158","name":"irc0","state":"running"}},{"created-at":"2020-09-03T06:25:04Z","name":"irc0_ROOT-634489_20200903042504","id":"7bd39d6f-8528-45c9-aed1-5d3d2da0b11b","state":"ready","instance":{"id":"e8db5c21-da06-4bb0-adb1-2f914972e158","name":"irc0","state":"running"}},{"created-at":"2020-07-06T15:25:34Z","name":"vpn0_ROOT-846459_20200706132534","id":"0c4a8776-aeb8-4189-9033-54a53c06a34c","state":"exported","instance":{"id":"0e713d4c-9f3f-4a9a-b958-b4571450d3a8","name":"vpn0","state":"running"}}]}'
```

2020-09-10 22:15 UTC, mristin approved these changes

2020-09-10 22:15 UTC, merged

2020-09-10 22:15 UTC, mristin commented
@falzm  thanks again for the code!